Update patch set 5
Patch Set 5: Code-Review-1

As you updated functions behaviour, this is breaking unit tests. What you need to do is update unit tests regarding the changes you made.

Results of the Jenkins job :

Failed tests: 
  NetworkHandlerTest.testCanCreateNetwork:76 Error, did not return the correct HTTP flag expected:<201> but was:<200>
  NetworkHandlerTest.testProcessEvent:143 
Wanted but not invoked:
networkHandler.canDeleteNetwork(<any>);
-> at org.opendaylight.ovsdb.openstack.netvirt.NetworkHandlerTest.testProcessEvent(NetworkHandlerTest.java:143)

However, there were other interactions with this mock:
-> at org.opendaylight.ovsdb.openstack.netvirt.NetworkHandlerTest.testProcessEvent(NetworkHandlerTest.java:106)
-> at org.opendaylight.ovsdb.openstack.netvirt.NetworkHandlerTest.testProcessEvent(NetworkHandlerTest.java:110)
-> at org.opendaylight.ovsdb.openstack.netvirt.NetworkHandlerTest.testProcessEvent(NetworkHandlerTest.java:141)

  PortHandlerTest.testCanCreatePort:64 Error, did not return the correct HTTP flag expected:<201> but was:<200>
  PortHandlerTest.testCanUpdatePort:70 Error, did not return the correct HTTP flag expected:<400> but was:<200>
  SubnetHandlerTest.testCanCreateSubnet:40 Error, canCreateSubnet() did not return the correct HTTP flag expected:<201> but was:<200>
  SubnetHandlerTest.testCanDeleteSubnet:50 Error, canDeleteSubnet() did not return the correct HTTP flag expected:<201> but was:<200>
  SubnetHandlerTest.testCanUpdateSubnet:45 Error, canUpdateSubnet() did not return the correct HTTP flag expected:<201> but was:<200>



Tests run: 108, Failures: 7, Errors: 0, Skipped: 0

Patch-set: 5
Label: Code-Review=-1