Update patch set 9
Patch Set 9:

Suneelu,
The l2gw netvirt csit test fails because of bug 9166. We need to get that patch merged and rerun the test.

https://bugs.opendaylight.org/show_bug.cgi?id=9166


Here is the exception log from the the csit run for this patch. You can see this log in this file:

https://logs.opendaylight.org/releng/jenkins092/netvirt-csit-hwvtep-1node-openstack-pike-gate-stateful-oxygen/2/odl1_karaf.log.gz

java.lang.IllegalStateException: No match found
	at java.util.regex.Matcher.group(Matcher.java:536)[:1.8.0_141]
	at org.opendaylight.ovsdb.utils.southbound.utils.SouthboundUtils.compareDbVersionToMinVersion(SouthboundUtils.java:1233)[375:org.opendaylight.ovsdb.utils.southbound-utils:1.6.0.SNAPSHOT]
	at org.opendaylight.netvirt.elan.l2gw.jobs.AssociateHwvtepToElanJob.createLogicalSwitch(AssociateHwvtepToElanJob.java:109)[316:org.opendaylight.netvirt.elanmanager-impl:0.6.0.SNAPSHOT]
	at org.opendaylight.netvirt.elan.l2gw.jobs.AssociateHwvtepToElanJob.call(AssociateHwvtepToElanJob.java:82)[316:org.opendaylight.netvirt.elanmanager-impl:0.6.0.SNAPSHOT]

Patch-set: 9