Update patch set 2
Patch Set 2:

Many of the ovsdb-verify jobs are failing due to unrelated karaf tests pointing to :

java.io.IOException: Error resolving artifact org.opendaylight.controller:netconf-auth:jar:0.2.5-SNAPSHOT: Could not find artifact org.opendaylight.controller:netconf-auth:jar:0.2.5-SNAPSHOT in defaultlocal (file:/opt/jenkins-ovsdb/.m2/repository/)

This is a controller karaf feature issue & other projects are being impacted due to this.

Due to that, we have decided to disable Karaf Feature tests in OVSDB project on verify.

Patch-set: 2
Label: Verified=0