Squashed commit of the following:
commit 6b73e082960a167ae9cb2f04b67e76936c1047da
Author: Anil Vishnoi <vishnoianil@gmail.com>
Date:   Sat Jul 18 18:58:31 2015 -0700

    Bug 3378 - ovsdb netvirt needs help in getting mac for a given ip in br-ex

    Added periodic refresh of gateway mac address
    Fixed packet deserialization exception

    Change-Id: Ib898347770cee213883c5222649b267efb4c701a
    Signed-off-by: Anil Vishnoi <vishnoianil@gmail.com>

commit 6568252fd403a9d7008041db96ee6936a53c7ead
Merge: bd9eb03 6f03720
Author: Anil Vishnoi <vishnoianil@gmail.com>
Date:   Tue Aug 11 17:05:26 2015 +0000

    Merge "Revert "Remove incorrect or unnecessary relativePaths""

commit 6f037203205aca8c57d6c0b476cdb0f5ff7172ab
Author: Flavio Fernandes <ffernand@redhat.com>
Date:   Tue Aug 11 16:47:45 2015 +0000

    Revert "Remove incorrect or unnecessary relativePaths"

    [12:45:12]  <zxiiro>	flaviof: we need ot revert that last one it breaks autorelease

    This reverts commit f9e874496792523a80586bdbade89b1a5c4f1bb9.

    Change-Id: Id6efe3dc5466d529174ea8f5214ad0ea93f74f97
    Signed-off-by: Flavio Fernandes <ffernand@redhat.com>

commit bd9eb036f7f27f1b457d3278c990429773f66c8e
Merge: f96c52f f9e8744
Author: Flavio Fernandes <ffernand@redhat.com>
Date:   Tue Aug 11 16:44:33 2015 +0000

    Merge "Remove incorrect or unnecessary relativePaths"

commit f9e874496792523a80586bdbade89b1a5c4f1bb9
Author: Stephen Kitt <skitt@redhat.com>
Date:   Tue Aug 11 17:34:15 2015 +0200

    Remove incorrect or unnecessary relativePaths

    For external modules, relativePath doesn't make much sense.
    For internal modules, an empty relativePath can be safely deleted.

    Change-Id: Ib67b950d1821797be677cc6524e5d387f415479e
    Signed-off-by: Stephen Kitt <skitt@redhat.com>

commit f96c52ffad6c6d821a4626410663ee3798606f99
Author: Thanh Ha <thanh.ha@linuxfoundation.org>
Date:   Sun Aug 9 12:07:55 2015 -0400

    Fix license header violations in ovs-sfc

    Change-Id: Ic9d46b75c5dceeb841a1aa8c3b879ee01ef05fee
    Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

commit 5cc54a650252732baa4715ebc4a2cb080762479e
Author: Thanh Ha <thanh.ha@linuxfoundation.org>
Date:   Sun Aug 9 12:05:43 2015 -0400

    Fix license header violations in plugin-mdsal-adapter

    Change-Id: Ibd122f1560d5dd60adb7d4cfa8b1e6840aac1bc9
    Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

commit 28408824af03464dbb5565d0c455c465e378ebf0
Author: Thanh Ha <thanh.ha@linuxfoundation.org>
Date:   Sun Aug 9 12:04:53 2015 -0400

    Fix license header violations in plugin-shell

    Change-Id: I2a0241223f5fe2ff135c44f53d9416e3a320b96c
    Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

commit 6d2d577dd3cc4672e525e8cef02d709c36e23b11
Author: Thanh Ha <thanh.ha@linuxfoundation.org>
Date:   Sun Aug 9 12:03:54 2015 -0400

    Fix license header violations in ovsdb-plugin-compatibility-layer

    Change-Id: I142a177ed8573ede4de41d225ea30e18b2c866f3
    Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

commit 765f8691fb67328fa922e22477923f4dc0d6e533
Author: Thanh Ha <thanh.ha@linuxfoundation.org>
Date:   Sun Aug 9 12:01:59 2015 -0400

    Fix license header violations in northbound

    Change-Id: Ie2f8925c84f377e718614dd11a501ca9ccc1b102
    Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

commit a75b255a3a350afe4555aa6ece92136354bee526
Author: Thanh Ha <thanh.ha@linuxfoundation.org>
Date:   Sun Aug 9 12:00:05 2015 -0400

    Fix license header violations in plugin

    Change-Id: I2cce1802191dd310bf29dc21e9edb26740d6a9f5
    Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

commit f40546bad5478de4862d265e451498e7d30bfa49
Author: Thanh Ha <thanh.ha@linuxfoundation.org>
Date:   Sun Aug 9 11:57:20 2015 -0400

    Fix license header violations in schemas

    Change-Id: I2a9685866015fd7f9e28872dee4a00e230da107d
    Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

commit adf8243deafed879129f042fa7c2d9b3c81392e8
Author: Thanh Ha <thanh.ha@linuxfoundation.org>
Date:   Sun Aug 9 11:54:30 2015 -0400

    Fix license header violations in library

    Change-Id: I8f070f8841200bc6233d51b7d918625a44e25587
    Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

commit 155b4a6754449472e29e8fd3b1eb8f9678ba1de4
Author: Thanh Ha <thanh.ha@linuxfoundation.org>
Date:   Sun Aug 9 11:38:32 2015 -0400

    Fix license header violations in net-virt-providers

    Change-Id: Id60cb77eb7b2b16135a7ad99d71f4d3967b615bb
    Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

commit da9c3ca2d8e2faf157280a0542546bc51ecd0d62
Author: Thanh Ha <thanh.ha@linuxfoundation.org>
Date:   Sun Aug 9 11:35:48 2015 -0400

    Fix license header violations in net-virt

    Change-Id: Ic98613d026ad820a801c0c5a15c898991303aaeb
    Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

commit aff63039f73a38a0df877d3a7f392c7ea422cb60
Author: Thanh Ha <thanh.ha@linuxfoundation.org>
Date:   Sun Aug 9 11:26:15 2015 -0400

    Fix license header violations in utils

    Change-Id: I0ba65c11fa293a190ef64bca3fea2244933013a8
    Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

commit 76f2a32a953977d43dad0ba01d1d72144fc44a88
Author: Thanh Ha <thanh.ha@linuxfoundation.org>
Date:   Sun Aug 9 11:21:55 2015 -0400

    Fix license header violations in southbound

    Change-Id: I6fa3bee147742b5bdd3fee92b8194518e091f21b
    Signed-off-by: Thanh Ha <thanh.ha@linuxfoundation.org>

commit 345b150dcdee6aa60c1a92f4213fac2396dbadfb
Author: Stephen Kitt <skitt@redhat.com>
Date:   Fri Aug 7 15:08:01 2015 +0200

    Use interfaces rather than classes where appropriate

    Change-Id: I0be41dca79638ace21900f97182ab0648e89fdcc
    Signed-off-by: Stephen Kitt <skitt@redhat.com>

commit ed5419c3f56a3f623631b0b63d3bfb2d43b5b603
Merge: 974f087 80aaf17
Author: Sam Hague <shague@redhat.com>
Date:   Fri Aug 7 00:32:27 2015 +0000

    Merge "Bug fix for 3545"

commit 974f0877ad95ebf785c48efe157151aab48027c7
Merge: 70c8e0f 5a4954e
Author: Sam Hague <shague@redhat.com>
Date:   Fri Aug 7 00:18:16 2015 +0000

    Merge "Clean up Maven dependencies (part 1)"

commit 80aaf175140202e9d1db6c079a3c3ee1bf87225e
Author: Sharad Mishra <sharad.d.mishra@intel.com>
Date:   Tue Jul 21 17:10:06 2015 -0400

    Bug fix for 3545

    https://bugs.opendaylight.org/show_bug.cgi?id=3545

    Change-Id: If216444c19d5457b0da08104ff19b227441b8801
    Signed-off-by: Sharad Mishra <sharad.d.mishra@intel.com>

commit 70c8e0fcda40ebc00620b24b01cda8ec93e61441
Author: Stephen Kitt <skitt@redhat.com>
Date:   Fri Jul 24 16:07:50 2015 +0200

    General Sonar clean-up

    Return simplification in a number of places:
    * drop useless return at the end of void methods (unless it comes before
      commented code)
    * simplify return ... ? true : false
    * simplify variable declaration immediately followed by return

    Drop unused local variables, and move some declarations closer to first
    use (in particular when there's a redundant initialisation value).

    Drop unused fields where it's safe to do so; in particular,
    OvsdbClientImpl's exceptions were never initialised so we can even drop
    the corresponding getter.

    Drop unnecessary casts and use the Java 7 <> operator as appropriate.

    Use primary types instead of wrappers where appropriate (dpid,
    openFlowPort).

    Drop redundant final modifiers on static methods.

    Drop redundant .toString() calls.

    Use .parseInt(), .parseShort() etc. instead of .decode().

    Drop a few dead methods.

    Avoid calling new String() explicitly.

    Drive-by cleaning:
    * AbstractHandler:
      - switch instead of multiple ifs
    * BridgeConfigurationManagerImpl, ConfigurationServiceImpl:
      - rework getControllerIPAddress() to loop over the configuration
        properties
      - in getNormalizedRow(), avoid rebuilding the array every time we go
        through the loop
    * ConfigurationServiceImpl:
      - in getTunnelEndPoint(), trace the tunnel endpoint only if we get
        one (avoids a NPE)
    * EgressAclService, IngressAclService:
      - srcIpPrefix only makes sense if securityRuleIpPrefix != null, so
        move into the corresponding block

    Change-Id: I7ca2a1a37f4795b3c0141b2b3a00977a15ffa5dd
    Signed-off-by: Stephen Kitt <skitt@redhat.com>

commit 5a4954e8bc7109f088ce5a95cb35ee2f33120ae0
Author: Stephen Kitt <skitt@redhat.com>
Date:   Wed Aug 5 10:53:57 2015 +0200

    Clean up Maven dependencies (part 1)

    Remove unused dependencies, and explicitly declare dependencies
    which are used directly (and used to be pulled in transitively).
    This will help future work on odlparent and upgrading upstream
    dependencies, as well as stabilising the dependencies on other
    ODL projects.

    The changes necessary were determined using
    dependency:analyze-report.

    Change-Id: Ie3ac0a6e4a98c69e253b9c851e7b0d5dc5f3ded8
    Signed-off-by: Stephen Kitt <skitt@redhat.com>

commit 11bf1a7d1be24e8bbddb51f3a029014a861bfdc5
Author: Sam Hague <shague@redhat.com>
Date:   Thu Aug 6 14:36:48 2015 +0000

    Revert "Support Jackson 2.5"

    This reverts commit 70b00fe87a469abadf37f84602d436efe358b5cb.

    This patch was created in response to c464b9a2a63c4ff41468b2e20ac48db806c918d6 in odlparent. That patch caused other failures so it was reverted and now this patch is reverted til the issues are fixed.

    Change-Id: I7025b96a2fd43eec50ca4f0d405e4ceedf88bdf4
    Signed-off-by: Sam Hague <shague@redhat.com>

commit 70b00fe87a469abadf37f84602d436efe358b5cb
Author: Stephen Kitt <skitt@redhat.com>
Date:   Wed Aug 5 11:16:27 2015 +0200

    Support Jackson 2.5

    TypeIdResolver added a new variant of typeFromId(), support that
    in OvsdbTypesIdResolver.

    (Apparently this class isn't used anywhere, so it might be better
    to delete it instead...)

    Change-Id: Iffe0a13fb84517cf2479189320e5c284ca68e941
    Signed-off-by: Stephen Kitt <skitt@redhat.com>

commit a80cdc87d3c8c8f2003be3069606d9e3b26b7114
Author: Stephen Kitt <skitt@redhat.com>
Date:   Tue Aug 4 13:52:51 2015 +0200

    Use parent version for maven-dependency-plugin

    Change-Id: Id04c7d3cf54b43c68b1de78059f0ad02d153e9d4
    Signed-off-by: Stephen Kitt <skitt@redhat.com>

commit f588dc86d5d1f6ad3315357ad7f6ffc12ac45067
Merge: 611b7f0 eaad725
Author: Flavio Fernandes <ffernand@redhat.com>
Date:   Sat Jul 25 01:22:08 2015 +0000

    Merge "Clean up logging"

commit eaad725c9a88f067325f3a36bb0f51d7077b55dd
Author: Stephen Kitt <skitt@redhat.com>
Date:   Fri Jul 24 15:58:09 2015 +0200

    Clean up logging

    Clean up logger declarations as per
    https://wiki.opendaylight.org/view/Logging_Best_Practices: always
    specify
        private static final Logger LOG = LoggerFactory.getLogger(...)
    and use parameterised logging.

    Change-Id: Ia6eb26588c631a52483b059d10d752b00daf5a98
    Signed-off-by: Stephen Kitt <skitt@redhat.com>

commit 611b7f07b507e4bea1e3daf205f5237d818d0ce0
Author: Stephen Kitt <skitt@redhat.com>
Date:   Fri Jul 24 15:21:16 2015 +0200

    Indicate that RefType values need to be lower-case

    Sonar complains that RefType's values should be upper-cased (as
    constants), but since they match JSON values they need to be lower-case.

    While we're at it, drop an unnecessary null declaration, remove the
    redundant static modifier from RefType, and merge two if statements.

    Change-Id: I98c7baf63cf42784ba40416bff96259ae8327084
    Signed-off-by: Stephen Kitt <skitt@redhat.com>

commit 7a50e3d6f924bce0d110345c2de0c3146bf3876a
Author: Flavio Fernandes <ffernand@redhat.com>
Date:   Wed Jul 22 15:21:36 2015 -0400

    Explicitly set git-review branch to master

    Change-Id: Ic5c7989ade5262f846bbad7f5a36bf8754542aab
    Signed-off-by: Flavio Fernandes <ffernand@redhat.com>
    Also-By: Thanh Ha <thanh.ha@linuxfoundation.org>

commit ee5ee1ea2422617d3580b124f4efd9b55e9b0b1d
Author: Stephen Kitt <skitt@redhat.com>
Date:   Wed Jul 22 15:22:18 2015 +0200

    Allow NetvirtIT to determine its karaf version

    Pax Exam needs a dependency on karaf so
    AbstractConfigTestBase::getKarafDistro() can determine the appropriate
    version.

    Change-Id: I7edd30e4698ec5aa9f417e396e38f5408d7b2645
    Signed-off-by: Stephen Kitt <skitt@redhat.com>

commit d523fb0d753d01db2ddc5c60b846802062af20f0
Author: Stephen Kitt <skitt@redhat.com>
Date:   Wed Jul 22 11:11:47 2015 +0200

    Allow SouthboundIT to determine its southbound-karaf version

    Since AbstractConfigTestBase::getKarafDistro() now uses
    versionAsInProject(), Pax Exam needs a dependency on southbound-karaf so
    it can determine the appropriate version.

    Change-Id: Icbfaab256ef9500982dcf13dbf2a2b68334bcda0
    Signed-off-by: Stephen Kitt <skitt@redhat.com>

commit 7294800ac6226194f7c75e1bce753ac04ab42afb
Merge: eb7cc0e 3f97968
Author: Flavio Fernandes <ffernand@redhat.com>
Date:   Tue Jul 21 21:54:50 2015 +0000

    Merge "Remove all redundant public modifiers in interfaces"

commit eb7cc0e1ab601d3da40bc61d9e9362e36e4cc7f4
Merge: 9bb6777 4bacbbc
Author: Sam Hague <shague@redhat.com>
Date:   Tue Jul 21 12:53:48 2015 +0000

    Merge "Sonar clean-up: OF13Provider"

commit 9bb6777df0c48e020199d682686231439442cd11
Merge: 052405e 74dde8f
Author: Sam Hague <shague@redhat.com>
Date:   Tue Jul 21 12:47:31 2015 +0000

    Merge "Add libvirt support"

commit 74dde8f7067b5d30a6eb48bd73697c64feadc0c2
Author: Stephen Kitt <skitt@redhat.com>
Date:   Tue Jul 21 14:26:13 2015 +0200

    Add libvirt support

    Set up memory sizes with libvirt. I'm not familiar enough with Ruby to
    know if there's a way of combining the :virtualbox and :libvirt
    stanzas...

    (The box images still need to be mutated manually.)

    Change-Id: Ic2d2531f4e696127155cf1522899591f61c7fa6e
    Signed-off-by: Stephen Kitt <skitt@redhat.com>

commit 052405e95f1a62e5af91e2bb2b7cb98d1329f728
Author: Flavio Fernandes <ffernand@redhat.com>
Date:   Mon Jul 20 18:49:53 2015 -0400

    Update showOvsdbMdsal.py to display bridge name and mac next to alias

    Change-Id: Ida68f52803737eb06bda03bbcc4ccf36758ab046
    Signed-off-by: Flavio Fernandes <ffernand@redhat.com>

commit 3f979683755908e83b082fd77e445d2f361809a8
Author: Stephen Kitt <skitt@redhat.com>
Date:   Mon Jul 20 16:49:37 2015 +0200

    Remove all redundant public modifiers in interfaces

    The public modifier is unnecessary in interfaces, their contents are
    public by default.

    Change-Id: Id307c25a9a704332dc75032432d1d2755bb3360e
    Signed-off-by: Stephen Kitt <skitt@redhat.com>

commit 4bacbbca7d0d501acbefd6f70358dd9c68121b56
Author: Stephen Kitt <skitt@redhat.com>
Date:   Fri Jul 17 15:30:06 2015 +0200

    Sonar clean-up: OF13Provider

    This class contains lots of methods with unused parameters, but they
    follow a pattern so override that instead of cleaning up the
    parameters.

    Dead-code elimination (unused methods, unnecessary initialisations).
    Code which corresponds to comment method calls is marked as such so
    it no longers causes Sonar warnings (with a TODO added to check the
    call sites).

    getTunnelReadinessStatus() appears unused but is tested for in the
    corresponding unit-test class, so keep it for now and override the
    unused warning.

    Long dpid -> long dpid.

    if (!local) {} if (local) {} -> if (!local) {} else {} (the value of
    local doesn't change in the first block).

    networkingProviderManager is initialised and used in a single method,
    so convert it to a local variable and adjust the corresponding test.

    Return value simplification (? true : false isn't necessary).

    <> operator in OF13ProviderTest.

    Change-Id: Ibf74d332257f063ffc603e663b1707829ddaa6e3
    Signed-off-by: Stephen Kitt <skitt@redhat.com>

commit 5ad41dc93d63a30f0f674b5e781e789cc377831e
Author: Anil Vishnoi <vishnoianil@gmail.com>
Date:   Tue Jul 7 16:50:43 2015 -0700

    Bug 3378 - ovsdb netvirt needs help in getting mac for a given ip in br-ex

    This patch, does not do periodic refresh of gateway mac. Will push that in next gerrit.

    Change-Id: Ie1a5a81fb7f196874f87bfbe0095ea595756a0a4
    Signed-off-by: Anil Vishnoi <vishnoianil@gmail.com>
    (cherry picked from commit 65a8de37c522f8f09caf6be73997906b98fd0b89)

commit 469a0d04a9385f55d5792cf2b72dac0c5aa02a38
Author: Flavio Fernandes <ffernand@redhat.com>
Date:   Fri Jul 17 12:14:22 2015 -0400

    Fix it failure: Error resolving artifact

    Fix the following issue:
    error: java.io.IOException: Error resolving artifact org.opendaylight.ovsdb:southbound-karaf:zip:1.1.0-SNAPSHOT

    In it builds, such as:
    https://jenkins.opendaylight.org/releng/view/ovsdb/job/ovsdb-daily-full-lithium-integration/OVS_VERSION=2.3.0,jdk=openjdk7,nodes=dynamic_docker/

    Change-Id: I91daf9655879369eb3512e653223b0c4c1e084bb
    Signed-off-by: Flavio Fernandes <ffernand@redhat.com>

commit 29402767d9136ed34e712d53ad21586e4ae3f4a7
Merge: c4a3d90 39d5dc2
Author: Flavio Fernandes <ffernand@redhat.com>
Date:   Fri Jul 17 14:04:09 2015 +0000

    Merge "Sonar clean-up: braces for control statements"

commit c4a3d90b6efa3e39a94721443af9725e3fbb459b
Merge: a51497f 8565b77
Author: Sam Hague <shague@redhat.com>
Date:   Fri Jul 17 11:32:32 2015 +0000

    Merge "Added fixed DHCP security rules, which will be added on a VM create."

commit 39d5dc217b0867b66db59212c6fb79646cca03ad
Author: Stephen Kitt <skitt@redhat.com>
Date:   Fri Jul 17 11:22:49 2015 +0200

    Sonar clean-up: braces for control statements

    Add braces for if, while, for statements. (Automated, thanks IntelliJ!)

    In a few cases a different change was more appropriate:
    * ConfigurationServiceImpl.java: in unsetOvsdbConfigurationService(),
      the if is redundant, we might as well set to null unconditionnally.
    * ConnectionServiceImpl.java: likewise
    * OvsdbLibraryIt.java: instead of
      if (...) { return true; } return false;
      just
      return ...;
    * OvsdbVswitchdSchemaConstants.java: likewise

    Change-Id: Ib35b395a64c3caa17c32a3f51c763d8a2f88b093
    Signed-off-by: Stephen Kitt <skitt@redhat.com>

commit 8565b7700aa90efbf849472d10e9b4c41a403abe
Author: Aswin Suryanarayanan <aswin.suryanarayanan@hp.com>
Date:   Mon Jul 6 20:09:52 2015 +0530

    Added fixed DHCP security rules, which will be added on a VM create.

    Change-Id: I8652c986acf3488ddf661ed265bff4cf6fb5ed1e
    Signed-off-by: Aswin Suryanarayanan <aswin.suryanarayanan@hp.com>

commit a51497fb73ba88ab096e7b375aab66b83c740db5
Author: Stephen Kitt <skitt@redhat.com>
Date:   Thu Jul 16 16:37:00 2015 +0200

    Clean-up in BridgeOperationalState

    The main fix is moving null-checks on iid before their first use.

    db and changes are only used in the constructor, they don't need to
    be in the instance; since the class isn't serializable removing the
    fields doesn't change anything external.

    Java 7 improvements: <> operator and merged exceptions.

    Use Optional.fromNullable() to simplify some Optional creation code
    and avoid double calls to getAugmentation().

    Change-Id: Id6b8a13c46d2b38b23f215f200314151b9eb2b0a
    Signed-off-by: Stephen Kitt <skitt@redhat.com>

Change-Id: I529731894bbd4fe3cd3db3d03643b58cd96822c2
Signed-off-by: Flavio Fernandes <ffernand@redhat.com>