Update patch set 2
Patch Set 2:

The Jenkins failure is not related to this patch.

1. Notice that my first patch passed Jenkins.
2. I did a fresh branch checkout, and see same error, different feature install failure:


 T E S T S
-------------------------------------------------------
Running org.opendaylight.odlparent.featuretest.SingleFeatureTest
Tests run: 9, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 261.247 sec <<< FAILURE! - in org.opendaylight.odlparent.featuretest.SingleFeatureTest
installFeature(org.opendaylight.odlparent.featuretest.SingleFeatureTest)[repoUrl: file:/home/Vic/git-clean/ovsdb/features/target/classes/features.xml, Feature: odl-ovsdb-openstack 1.3.0-SNAPSHOT]  Time elapsed: 89.696 sec  <<< ERROR!
java.lang.IllegalStateException: Can't install feature odl-ovsdb-openstack/1.3.0-SNAPSHOT: 
Could not start bundle mvn:org.opendaylight.ovsdb/openstack.net-virt/1.3.0-SNAPSHOT in feature(s) odl-ovsdb-openstack-clusteraware-1.3.0-SNAPSHOT, odl-ovsdb-openstack-1.3.0-SNAPSHOT: Unresolved constraint in bundle org.opendaylight.ovsdb.openstack.net-virt [303]: Unable to resolve 303.0: missing requirement [303.0] osgi.wiring.package; (&(osgi.wiring.package=org.apache.commons.net.util)(version>=3.4.0)(!(version>=4.0.0)))

Patch-set: 2