Update patch set 1
Patch Set 1: Code-Review-1

[ERROR] Failed to execute goal org.opendaylight.yangtools:yang-maven-plugin:0.7.0-SNAPSHOT:generate-sources (default) on project of-extension.nx-sal: yang-to-sources: Unable to parse yang files from /Users/ffernand/ODL/projects/ovsdb.git/of-extension/nx-sal/src/main/yang: Error in module 'packet-processing' at line 88: Can not add 'case nx-action-resubmit-rpc-transmit-packet-case' to node 'action' in module 'packet-processing': case with same name already declared at line 88 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.opendaylight.yangtools:yang-maven-plugin:0.7.0-SNAPSHOT:generate-sources (default) on project of-extension.nx-sal: yang-to-sources: Unable to parse yang files from /Users/ffernand/ODL/projects/ovsdb.git/of-extension/nx-sal/src/main/yang
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: org.apache.maven.plugin.MojoExecutionException: yang-to-sources: Unable to parse yang files from /Users/ffernand/ODL/projects/ovsdb.git/of-extension/nx-sal/src/main/yang
	at org.opendaylight.yangtools.yang2sources.plugin.YangToSourcesProcessor.processYang(YangToSourcesProcessor.java:177)
	at org.opendaylight.yangtools.yang2sources.plugin.YangToSourcesProcessor.execute(YangToSourcesProcessor.java:82)
	at org.opendaylight.yangtools.yang2sources.plugin.YangToSourcesMojo.execute(YangToSourcesMojo.java:122)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 25 more
Caused by: org.opendaylight.yangtools.yang.parser.util.YangParseException: Error in module 'packet-processing' at line 88: Can not add 'case nx-action-resubmit-rpc-transmit-packet-case' to node 'action' in module 'packet-processing': case with same name already declared at line 88
	at org.opendaylight.yangtools.yang.parser.builder.impl.ChoiceBuilder.addCase(ChoiceBuilder.java:173)
	at org.opendaylight.yangtools.yang.parser.builder.impl.BuilderUtils.fillAugmentTarget(BuilderUtils.java:314)
	at org.opendaylight.yangtools.yang.parser.builder.impl.BuilderUtils.fillAugmentTarget(BuilderUtils.java:264)
	at org.opendaylight.yangtools.yang.parser.builder.impl.BuilderUtils.processAugmentation(BuilderUtils.java:653)
	at org.opendaylight.yangtools.yang.parser.impl.YangParserImpl.resolveAugment(YangParserImpl.java:1009)
	at org.opendaylight.yangtools.yang.parser.impl.YangParserImpl.resolveAugments(YangParserImpl.java:914)
	at org.opendaylight.yangtools.yang.parser.impl.YangParserImpl.build(YangParserImpl.java:714)
	at org.opendaylight.yangtools.yang.parser.impl.YangParserImpl.parseYangModelSources(YangParserImpl.java:358)
	at org.opendaylight.yangtools.yang.parser.impl.YangParserImpl.parseYangModelsFromStreamsMapped(YangParserImpl.java:312)
	at org.opendaylight.yangtools.yang2sources.plugin.YangToSourcesProcessor.processYang(YangToSourcesProcessor.java:151)
	... 29 more
[ERROR]

Patch-set: 1
Label: Code-Review=-1