Update patch set 2
Patch Set 2: Code-Review-2

We discussed this by email, it turns out that the current epoll JARs don't work in an OSGi container.

On Tue, 3 May 2016 16:59:17 +0000
"Ranganathan, Dileep" <dileep.ranganathan@intel.com> wrote:
> You are right. Wrapping is sufficient to load it as bundle. 
> But I am facing an issue in 64-bit linux. It throws
> NoClassDefFoundError for one of the static class registered from
> JNI_OnLoad. I thought wrapping is causing this issue and doesn't load
> the class properly. I might be wrong.
> 
> Ideally if the architecture is not supported, Epoll.isAvailable()
> throws UnSatisfiedLinkError. But in 64-bit case it throws Caused by:
> java.lang. NoClassDefFoundError :
> io.netty.channel.epoll.NativeStaticallyReferencedJniMethods.   

So it appears that the NoClassDefFoundError is thrown because the
native library load request is handled by a classloader a few levels
up from the container's classloader, and that classloader doesn't know
about the Netty JARs. If I'm correct then it should be possible to tell
the JVM about the JAR and get things working that way (assuming we
don't end up with two separate definitions of the classes involved in
two different classloaders). The proper solution would of course be a
fix for https://github.com/netty/netty/issues/5119 ;-).

Patch-set: 2
Reviewer: Gerrit User 4540 <4540@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Code-Review=-2