Update patch set 1
Patch Set 1:

Hi Sam,
Good questions, responses below. 

The majority of tests pass with the docker image that has both schemas, except for southbound-it. Debugging that now. I'll update as I make progress.

vic, some questions:
1. maybe we should break this patch into two. one for the schema update and the next for the remove of the exclude since that is to run the hwvtepsouthbound tests

Maybe, I'm close to getting this working, I believe. Let's see how it looks after I get southbound-it, and make a call then. Sound OK?


2. does merging this patch depend on having the new ovs docker with hwvtep and open_vswitch schemas? The libraryIT should at least work since there are the assumes for the hwvtep pieces.


No, it doesn't. I ran library/it tests, without the hwvtep schema loaded, all 25 passed. As you point out, the hwvtep IT code has the assumeTrue, and bails because the hardware_vtep schema is not loaded. 

2016-06-15 10:17:26,944 | INFO  | n(3)-172.17.40.6 | AbstractConfigTestBase           | 214 - PAXEXAM-PROBE-6c1ea63a-ddbc-4d6a-8c89-c589f9d60711 - 0.0.0 | TestWatcher: Test skipped: testManager(org.opendaylight.ovsdb.integrationtest.schema.HardwareVTEPIT) 
org.junit.AssumptionViolatedException: hardware_vtep is required.


[root@rippleRider docker-ovs]# cid=$(docker run -idt --cap-add NET_ADMIN -p 6641:6640 vpickard/ovs-hwvtep)
[root@rippleRider docker-ovs]# docker exec $cid ps -elf
PID   USER     COMMAND
    1 root     {supervisord} /usr/bin/python /usr/bin/supervisord
    9 root     {supervisor_stdo} /usr/bin/python /usr/bin/supervisor_stdout
   10 root     /usr/local/sbin/ovsdb-server /etc/openvswitch/conf.db --remote=punix:/usr/local/var/run/openvswitch/db.sock --remote=ptcp:6640 --pidfile=ovsdb-server.pid
   11 root     /usr/local/sbin/ovs-vswitchd -v --pidfile
   28 root     ps -elf

[root@rippleRider docker-ovs]# docker exec $cid ovs-vsctl set-manager ptcp:6640
[root@rippleRider docker-ovs]# docker exec $cid ovs-vsctl show
8c402d51-62c8-41b3-9c2e-d0b120cec9bf
    Manager "ptcp:6640"
    ovs_version: "2.4.0"

[root@rippleRider docker-ovs]# docker exec $cid ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:12:00:02  
          inet addr:172.18.0.2  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe12:2/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:648 (648.0 B)  TX bytes:648 (648.0 B)

[Vic@rippleRider$][~/git/ovsdb/library/it] (master $>)$ mvn -nsu verify -Dmaven.compile.fork=true -Dcheckstyle.skip -Pintegrationtest -Dovsdbserver.ipaddress=172.18.0.2


Results :

Tests run: 25, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-failsafe-plugin:2.18.1:verify (default) @ library-it ---
[INFO] Failsafe report directory: /home/Vic/git/ovsdb/library/it/target/surefire-reports
[INFO] 
[INFO] --- maven-source-plugin:3.0.0:jar-no-fork (attach-sources) @ library-it ---
[INFO] No sources in project. Archive not created.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.2.201409121644:report (post-unit-test) @ library-it ---
[INFO] Analyzed bundle 'library-it' with 0 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:49 min
[INFO] Finished at: 2016-06-15T10:19:55-04:00
[INFO] Final Memory: 55M/544M
[INFO] ------------------------------------------------------------------------
[Vic@rippleRider$][~/git/ovsdb/library/it] (master $>)$ 



3. What was the final method to test if both schemas are loaded? I was under the impression the ovsdb service had to be listening on two different ports to with the schema per port. If so, we would need a second param for the second port to start the hwvtep tests.

[root@rippleRider docker-ovs]# docker exec $cid ovsdb-client list-dbs
Open_vSwitch
hardware_vtep
[root@rippleRider docker-ovs]# 

Here, you can see both schemas loaded. From logs and debug below, you can see that ovsdb service is able to connect to the ovsdb node for both schemas. So, it seems to be working without any change to listen on different ports for each schema. Do you recall the reference where you saw this requirement? From what I see, this just works, but I'll keep investigating if you think some additional code/config is needed.

When testing, I attached to the docker container, and can see OVS logs when library/it tests are running. Here is a sample:

ovs-vswitchd stderr | 2016-06-15T14:19:53Z|00696|jsonrpc|DBG|unix:/usr/local/var/run/openvswitch/db.sock: received notification, method="update", params=[null,{"Flow_Sample_Collector_Set":{"126aafb4-acad-4b2b-aac2-1d14800f3057":{"new":{"id":1,"ipfix":["set",[]],"bridge":["uuid","b627cc54-1e92-42df-aaba-d7cadfe02a65"]}}}}]
2016-06-15T14:19:53Z|00697|dpif|WARN|failed to enumerate system datapaths: No such file or directory
2016-06-15T14:19:53Z|00698|dpif|WARN|failed to create datapath ovs-system: No such file or directory
2016-06-15T14:19:53Z|00699|ofproto_dpif|ERR|failed to open datapath of type system: No such file or directory
2016-06-15T14:19:53Z|00700|ofproto|ERR|failed to open datapath br_test: No such file or directory
2016-06-15T14:19:53Z|00701|bridge|ERR|failed to create bridge br_test: No such file or directory
ovs-vswitchd stderr | 2016-06-15T14:19:53Z|00702|poll_loop|DBG|wakeup due to [POLLIN] on fd 7 (<->/usr/local/var/run/openvswitch/db.sock) at lib/stream-fd.c:155 (0% CPU usage)
ovs-vswitchd stderr | 2016-06-15T14:19:53Z|00703|jsonrpc|DBG|unix:/usr/local/var/run/openvswitch/db.sock: received notification, method="update", params=[null,{"Flow_Sample_Collector_Set":{"126aafb4-acad-4b2b-aac2-1d14800f3057":{"old":{"id":1,"ipfix":["set",[]],"bridge":["uuid","b627cc54-1e92-42df-aaba-d7cadfe02a65"]}}}}]
2016-06-15T14:19:53Z|00704|dpif|WARN|failed to enumerate system datapaths: No such file or directory
2016-06-15T14:19:53Z|00705|dpif|WARN|failed to create datapath ovs-system: No such file or directory
2016-06-15T14:19:53Z|00706|ofproto_dpif|ERR|failed to open datapath of type system: No such file or directory
2016-06-15T14:19:53Z|00707|ofproto|ERR|failed to open datapath br_test: No such file or directory
ovs-vswitchd stderr | 2016-06-15T14:19:53Z|00708|bridge|ERR|failed to create bridge br_test: No such file or directory
ovs-vswitchd stderr | 2016-06-15T14:19:53Z|00709|poll_loop|DBG|wakeup due to [POLLIN] on fd 7 (<->/usr/local/var/run/openvswitch/db.sock) at lib/stream-fd.c:155 (0% CPU usage)
ovs-vswitchd stderr | 2016-06-15T14:19:53Z|00710|jsonrpc|DBG|unix:/usr/local/var/run/openvswitch/db.sock: received notification, method="update", params=[null,{"Bridge":{"b627cc54-1e92-42df-aaba-d7cadfe02a65":{"old":{"name":"br_test","flood_vlans":34,"stp_enable":false,"ports":["set",[]],"auto_attach":["set",[]],"rstp_enable":false,"fail_mode":["set",[]],"rstp_status":["map",[]],"flow_tables":["map",[]],"netflow":["set",[]],"datapath_type":"","controller":["set",[]],"status":["map",[["key","value"]]],"ipfix":["set",[]],"other_config":["map",[]],"mirrors":["set",[]],"datapath_id":["set",[]],"mcast_snooping_enable":false,"protocols":["set",[]],"sflow":["set",[]],"datapath_version":""}}},"Open_vSwitch":{"8c402d51-62c8-41b3-9c2e-d0b120cec9bf":{"new":{"manager_options":["uuid","8b9d3a1d-a69d-47ac-837d-e7814b6d671e"],"bridges":["set",[]],"statistics":["map",[]],"other_config":["map",[]],"cur_cfg":1,"next_cfg":1,"iface_types":["set",["geneve","gre","gre64","internal","ipsec_gre","ipsec_gre64","lisp","patch","stt","system","tap","vxlan"]],"ssl":["set",[]],"datapath_types":["set",["netdev","system"]]},"old":{"bridges":["uuid","b627cc54-1e92-42df-aaba-d7cadfe02a65"]}}}}]
^C2016-06-15 14:25:05,118 WARN received SIGINT indicating exit request
2016-06-15 14:25:05,118 INFO waiting for stdout, ovs-vswitchd, ovsdb-server to die
^C2016-06-15 14:25:05,468 WARN received SIGINT indicating exit request
ovs-vswitchd stderr | 2016-06-15T14:25:06Z|00711|poll_loop|DBG|wakeup due to [POLLIN] on fd 4 (FIFO pipe:[14543772]) at lib/fatal-signal.c:224 (0% CPU usage)
ovs-vswitchd stderr | 2016-06-15T14:25:06Z|00712|fatal_signal|WARN|terminating with signal 15 (Terminated)
2016-06-15 14:25:06,480 INFO stopped: ovs-vswitchd (terminated by SIGTERM)
ovsdb-server stderr | 2016-06-15T14:25:06Z|00010|fatal_signal|WARN|terminating with signal 15 (Terminated)
2016-06-15 14:25:06,484 INFO stopped: ovsdb-server (terminated by SIGTERM)
^C2016-06-15 14:25:07,180 WARN received SIGINT indicating exit request
2016-06-15 14:25:07,185 INFO stopped: stdout (terminated by SIGTERM)

When running hwvtepsouthbound-it tests (only 5, need more here....), no OVS logs are observed from the container. (Maybe need some config to enable vtep logs...). So, I dumped the hardware vtep db while the test was running, just to make sure the db was touched. Here, you can see the physical switch ps0 being created/deleted:


[root@rippleRider docker-ovs]# docker exec $cid ovsdb-client dump unix:/usr/local/var/run/openvswitch/db.sock hardware_vtep
Arp_Sources_Local table
_uuid locator src_mac
----- ------- -------

Arp_Sources_Remote table
_uuid locator src_mac
----- ------- -------

Global table
_uuid                                managers                               switches                              
------------------------------------ -------------------------------------- --------------------------------------
ebce1400-3fbe-4b3f-bed6-dc191edfc5fb [a5c19b99-e941-4df5-9756-7804626f085a] [abf6cf96-689d-4122-a412-d747ddfc6ea5]

Logical_Binding_Stats table
_uuid bytes_from_local bytes_to_local packets_from_local packets_to_local
----- ---------------- -------------- ------------------ ----------------

Logical_Router table
_uuid description name static_routes switch_binding
----- ----------- ---- ------------- --------------

Logical_Switch table
_uuid description name tunnel_key
----- ----------- ---- ----------

Manager table
_uuid                                inactivity_probe is_connected max_backoff other_config status target     
------------------------------------ ---------------- ------------ ----------- ------------ ------ -----------
a5c19b99-e941-4df5-9756-7804626f085a []               false        []          {}           {}     "ptcp:6640"

Mcast_Macs_Local table
MAC _uuid ipaddr locator_set logical_switch
--- ----- ------ ----------- --------------

Mcast_Macs_Remote table
MAC _uuid ipaddr locator_set logical_switch
--- ----- ------ ----------- --------------

Physical_Locator table
_uuid dst_ip encapsulation_type
----- ------ ------------------

Physical_Locator_Set table
_uuid locators
----- --------

Physical_Port table
_uuid                                description name   port_fault_status vlan_bindings vlan_stats
------------------------------------ ----------- ------ ----------------- ------------- ----------
c366a60d-eedd-4644-978e-aaf62f72935f ""          "eth0" []                {}            {}        

Physical_Switch table
_uuid                                description         management_ips name    ports                                  switch_fault_status tunnel_ips         tunnels
------------------------------------ ------------------- -------------- ------- -------------------------------------- ------------------- ------------------ -------
abf6cf96-689d-4122-a412-d747ddfc6ea5 "OVS VTEP Emulator" []             br-vtep [c366a60d-eedd-4644-978e-aaf62f72935f] []                  ["192.168.254.20"] []     

Tunnel table
_uuid bfd_config_local bfd_config_remote bfd_params bfd_status local remote
----- ---------------- ----------------- ---------- ---------- ----- ------

Ucast_Macs_Local table
MAC _uuid ipaddr locator logical_switch
--- ----- ------ ------- --------------

Ucast_Macs_Remote table
MAC _uuid ipaddr locator logical_switch
--- ----- ------ ------- --------------
[root@rippleRider docker-ovs]# docker exec $cid ovsdb-client dump unix:/usr/local/var/run/openvswitch/db.sock hardware_vtep
Arp_Sources_Local table
_uuid locator src_mac
----- ------- -------

Arp_Sources_Remote table
_uuid locator src_mac
----- ------- -------

Global table
_uuid                                managers                               switches                                                                    
------------------------------------ -------------------------------------- ----------------------------------------------------------------------------
ebce1400-3fbe-4b3f-bed6-dc191edfc5fb [a5c19b99-e941-4df5-9756-7804626f085a] [5e93e49a-a90f-4af1-8479-9a66c3934080, abf6cf96-689d-4122-a412-d747ddfc6ea5]

Logical_Binding_Stats table
_uuid bytes_from_local bytes_to_local packets_from_local packets_to_local
----- ---------------- -------------- ------------------ ----------------

Logical_Router table
_uuid description name static_routes switch_binding
----- ----------- ---- ------------- --------------

Logical_Switch table
_uuid description name tunnel_key
----- ----------- ---- ----------

Manager table
_uuid                                inactivity_probe is_connected max_backoff other_config status target     
------------------------------------ ---------------- ------------ ----------- ------------ ------ -----------
a5c19b99-e941-4df5-9756-7804626f085a []               false        []          {}           {}     "ptcp:6640"

Mcast_Macs_Local table
MAC _uuid ipaddr locator_set logical_switch
--- ----- ------ ----------- --------------

Mcast_Macs_Remote table
MAC _uuid ipaddr locator_set logical_switch
--- ----- ------ ----------- --------------

Physical_Locator table
_uuid dst_ip encapsulation_type
----- ------ ------------------

Physical_Locator_Set table
_uuid locators
----- --------

Physical_Port table
_uuid                                description name   port_fault_status vlan_bindings vlan_stats
------------------------------------ ----------- ------ ----------------- ------------- ----------
c366a60d-eedd-4644-978e-aaf62f72935f ""          "eth0" []                {}            {}        

Physical_Switch table
_uuid                                description         management_ips name    ports                                  switch_fault_status tunnel_ips         tunnels
------------------------------------ ------------------- -------------- ------- -------------------------------------- ------------------- ------------------ -------
5e93e49a-a90f-4af1-8479-9a66c3934080 ""                  []             "ps0"   []                                     []                  []                 []     
abf6cf96-689d-4122-a412-d747ddfc6ea5 "OVS VTEP Emulator" []             br-vtep [c366a60d-eedd-4644-978e-aaf62f72935f] []                  ["192.168.254.20"] []     

Tunnel table
_uuid bfd_config_local bfd_config_remote bfd_params bfd_status local remote
----- ---------------- ----------------- ---------- ---------- ----- ------

Ucast_Macs_Local table
MAC _uuid ipaddr locator logical_switch
--- ----- ------ ------- --------------

Ucast_Macs_Remote table
MAC _uuid ipaddr locator logical_switch
--- ----- ------ ------- --------------
[root@rippleRider docker-ovs]# docker exec $cid ovsdb-client dump unix:/usr/local/var/run/openvswitch/db.sock hardware_vtep
Arp_Sources_Local table
_uuid locator src_mac
----- ------- -------

Arp_Sources_Remote table
_uuid locator src_mac
----- ------- -------

Global table
_uuid                                managers                               switches                              
------------------------------------ -------------------------------------- --------------------------------------
ebce1400-3fbe-4b3f-bed6-dc191edfc5fb [a5c19b99-e941-4df5-9756-7804626f085a] [abf6cf96-689d-4122-a412-d747ddfc6ea5]

Logical_Binding_Stats table
_uuid bytes_from_local bytes_to_local packets_from_local packets_to_local
----- ---------------- -------------- ------------------ ----------------

Logical_Router table
_uuid description name static_routes switch_binding
----- ----------- ---- ------------- --------------

Logical_Switch table
_uuid description name tunnel_key
----- ----------- ---- ----------

Manager table
_uuid                                inactivity_probe is_connected max_backoff other_config status target     
------------------------------------ ---------------- ------------ ----------- ------------ ------ -----------
a5c19b99-e941-4df5-9756-7804626f085a []               false        []          {}           {}     "ptcp:6640"

Mcast_Macs_Local table
MAC _uuid ipaddr locator_set logical_switch
--- ----- ------ ----------- --------------

Mcast_Macs_Remote table
MAC _uuid ipaddr locator_set logical_switch
--- ----- ------ ----------- --------------

Physical_Locator table
_uuid dst_ip encapsulation_type
----- ------ ------------------

Physical_Locator_Set table
_uuid locators
----- --------

Physical_Port table
_uuid                                description name   port_fault_status vlan_bindings vlan_stats
------------------------------------ ----------- ------ ----------------- ------------- ----------
c366a60d-eedd-4644-978e-aaf62f72935f ""          "eth0" []                {}            {}        

Physical_Switch table
_uuid                                description         management_ips name    ports                                  switch_fault_status tunnel_ips         tunnels
------------------------------------ ------------------- -------------- ------- -------------------------------------- ------------------- ------------------ -------
abf6cf96-689d-4122-a412-d747ddfc6ea5 "OVS VTEP Emulator" []             br-vtep [c366a60d-eedd-4644-978e-aaf62f72935f] []                  ["192.168.254.20"] []     

Tunnel table
_uuid bfd_config_local bfd_config_remote bfd_params bfd_status local remote
----- ---------------- ----------------- ---------- ---------- ----- ------

Ucast_Macs_Local table
MAC _uuid ipaddr locator logical_switch
--- ----- ------ ------- --------------

Ucast_Macs_Remote table
MAC _uuid ipaddr locator logical_switch
--- ----- ------ ------- --------------
[root@rippleRider docker-ovs]# 





4. I wonder if the test itself should be modified and the assumes removed. In the setup a assert is there to check for the requested schema. For hwvtep it is an assume so we should be able to remove the assumes in the actual test itself. Then we should probably change the open_vswitch to also use assume and punt.

Yes, I agree with this suggestion. Now that we have a docker image available that supports both schemas, the assumes should be changed to failures. I would propose to do this in a separate patch.



5. If both schemas are loaded, is there any conflict with the southbound and hwvtepsouthbound both running? We should run the IT from ovsdb/root against the one docker and see if everything passes.


southbound-it isn't working. Debugging now. Discovered this when I ran IT from ovsdb.

Patch-set: 1