[DO NOT MERGE] Hack to work around issue introduced in d6ea281e
https://gist.github.com/d75658860138b0f14ae6

[16:12:09]  <flaviof>	 folks: do any of you know the severity of this log: https://gist.github.com/d75658860138b0f14ae6
[16:12:16]  <flaviof>	 Madhu: ^^^
[16:12:38]  <flaviof>	 things are not working at all and I was trying to pick a thread to pull. :)
[16:14:44]  <@Madhu>	 flaviof: no idea :)
[16:15:02]  <flaviof>	 Madhu: ok. np. thanks anyway
[16:15:05]  <@Madhu>	 "java.lang.IllegalStateException: Previous transaction in chain must be ready." don't know what that means
[16:15:14]  <@Madhu>	 but i know what this code is :)
[16:15:15]  <flaviof>	 yeah, me neither :)
[16:15:40]  <@Madhu>     flaviof: AbstractServiceInstance listens to node update events
[16:15:44]  <@Madhu>     and installs flows
[16:15:44]  <flaviof>    Madhu: is this code something that can be 'disabled' w/out side effects?
[16:15:56]  <@Madhu>     flaviof: yep.
[16:16:13]  <flaviof>    i don't mean to check it in; just want to see if that works.

2014-09-03 16:09:44.533 EDT [md-sal-binding-notification-30] ERROR o.o.c.sal.binding.impl.NotifyTask - Unhandled exception thrown by listener: org.opendaylight.ovsdb.openstack.netvirt.providers.openflow13.services.L3ForwardingService$$Broker$ListenerInvoker@2eb4aca0
java.lang.IllegalStateException: Previous transaction in chain must be ready.
at com.google.common.base.Preconditions.checkState(Preconditions.java:149) ~[na:na]
at org.opendaylight.controller.md.sal.dom.store.impl.InMemoryDOMDataStore$DOMStoreTransactionChainImpl.newReadWriteTransaction(InMemoryDOMDataStore.java:227) ~[na:na]
at org.opendaylight.controller.md.sal.dom.broker.impl.AbstractDOMForwardedTransactionFactory.newReadWriteTransaction(AbstractDOMForwardedTransactionFactory.java:186) ~[na:na]
at org.opendaylight.controller.md.sal.binding.impl.BindingTranslatedTransactionChain.newReadWriteTransaction(BindingTranslatedTransactionChain.java:61) ~[na:na]
at org.opendaylight.ovsdb.openstack.netvirt.providers.openflow13.AbstractServiceInstance.onNodeUpdated(AbstractServiceInstance.java:311) ~[na:na]
at org.opendaylight.ovsdb.openstack.netvirt.providers.openflow13.services.L3ForwardingService$$Broker$ListenerInvoker.onNotification(L3ForwardingService$$Broker$ListenerInvoker.java) ~[na:na]
at org.opendaylight.controller.sal.binding.impl.AbstractNotificationListenerRegistration.notify(AbstractNotificationListenerRegistration.java:38) ~[na:na]
at org.opendaylight.controller.sal.binding.impl.NotifyTask.run(NotifyTask.java:42) ~[na:na]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_67]
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_67]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_67]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_67]
at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]
2014-09-03 16:09:44.533 EDT [md-sal-binding-notification-13] ERROR o.o.c.sal.binding.impl.NotifyTask - Unhandled exception thrown by listener: org.opendaylight.ovsdb.openstack.netvirt.providers.openflow13.services.OutboundNatService$$Broker$ListenerInvoker@5be13c7e
java.lang.IllegalStateException: Previous transaction in chain must be ready.
at com.google.common.base.Preconditions.checkState(Preconditions.java:149) ~[na:na]
at org.opendaylight.controller.md.sal.dom.store.impl.InMemoryDOMDataStore$DOMStoreTransactionChainImpl.newReadWriteTransaction(InMemoryDOMDataStore.java:227) ~[na:na]
at org.opendaylight.controller.md.sal.dom.broker.impl.AbstractDOMForwardedTransactionFactory.newReadWriteTransaction(AbstractDOMForwardedTransactionFactory.java:186) ~[na:na]
...

Change-Id: Ibd693414c2864e2fe3c0ad7076e0eecf822a2945
Signed-off-by: Flavio Fernandes <ffernand@redhat.com>