Merge branch 'master' to branch 'topic/master/neutron-yang-migration' Squashed commit of the following:
commit 833ea0aba76e3e3317ca6b7e2a0d6fc99a53d9db
Merge: 91de317 423e4d8
Author: Flavio Fernandes <ffernand@redhat.com>
Date:   Thu Oct 15 17:17:06 2015 +0000

    Merge "Adding copyright header to ovsdb/southbound UT"

commit 91de31748b01a61b80796d121753ac0dff154910
Author: Sam Hague <shague@redhat.com>
Date:   Thu Oct 15 12:08:13 2015 -0400

    Add postman collection for NetvirtSfc

    Change-Id: Ibe16df4c9d789311b185a9f7cb0193b7a81f5aba
    Signed-off-by: Sam Hague <shague@redhat.com>

commit 2989548e8b4191e2b050390f565789dddd6702f5
Author: Sam Hague <shague@redhat.com>
Date:   Thu Oct 15 09:50:46 2015 -0400

    Remove unused BundleContext from NetvirtSfc

    Change-Id: I7d9d185710f82546472d733796ebc2cba2e3a671
    Signed-off-by: Sam Hague <shague@redhat.com>

commit 423e4d84a8e2cf602222a9bfbefba9f20b79e382
Author: Rashmi Pujar <rpujar@inocybe.com>
Date:   Thu Oct 15 09:39:33 2015 -0400

    Adding copyright header to ovsdb/southbound UT

    Change-Id: I92d1f02491f04177b97a1ece879da9278220801b
    Signed-off-by: Rashmi Pujar <rpujar@inocybe.com>

commit ea352fced510fa638358b43a818adec60bfac0b3
Merge: 249630d f7f42fb
Author: Flavio Fernandes <ffernand@redhat.com>
Date:   Thu Oct 15 11:59:38 2015 +0000

    Merge "All TCP & UDP SG Rules : Implementation and Unit tests added."

commit 249630df31cdab5087fc44e32d44a4e082a12e40
Merge: 26b0027 26ed356
Author: Flavio Fernandes <ffernand@redhat.com>
Date:   Thu Oct 15 11:56:48 2015 +0000

    Merge "UT for southbound/transactions/md - set 5"

commit 26b0027005bbeb06bfe228e9dceecded20ad4724
Merge: cb2fb88 959688e
Author: Flavio Fernandes <ffernand@redhat.com>
Date:   Thu Oct 15 11:51:55 2015 +0000

    Merge "Bug 4472 - netvirt: IlligalArgumentException in NAT provider"

commit cb2fb8864b794f1a792d2614522ab36c27bd5c4d
Merge: 241ccfe e211414
Author: Sam Hague <shague@redhat.com>
Date:   Thu Oct 15 01:37:31 2015 +0000

    Merge "cleanup NetvirtSfcIT"

commit e211414c068a2f6ba80f1398ca0b38acbc67db42
Author: Sam Hague <shague@redhat.com>
Date:   Wed Oct 14 21:12:16 2015 -0400

    cleanup NetvirtSfcIT

    Change-Id: I1cc224a7ab4f65825feefe6de28fb787ca7e2f1c
    Signed-off-by: Sam Hague <shague@redhat.com>

commit 959688edc325bd4adec9e760da771aeedbb2712f
Author: Isaku Yamahata <isaku.yamahata@intel.com>
Date:   Wed Oct 14 15:06:19 2015 -0700

    Bug 4472 - netvirt: IlligalArgumentException in NAT provider

    This patch adds work around code for ipv6 cidr notation is given.
    Otherwise following exception occurs.

    > 2015-10-14 13:38:55,125 | ERROR | ntDispatcherImpl | NeutronL3Adapter                 | 392 - org.opendaylight.ovsdb.openstack.net-virt - 1.2.1.SNAPSHOT | ProgramRouterInterface failed for mac:FA:16:3E:E0:A8:B5 addr:fd14:5ac7:ba3::1/64 node:ovsdb://uuid/8f75c49c-52b9-4303-8633-a80f0361429b/bridge/br-int srcTunId:external destTunId:1083 action:ADD status:Not Implemented: Not Implemented (0)
    > 2015-10-14 13:38:55,126 | DEBUG | ntDispatcherImpl | ArpResponderService              | 393 - org.opendaylight.ovsdb.openstack.net-virt-providers - 1.2.1.SNAPSHOT | ipv6 address case is not implemented yet. dpid 209308480409166 segmentationId 1083 macAddressStr, ipAddress FA:16:3E:E0:A8:B5 action /fd14:5ac7:ba3:0:0:0:0:1
    > 2015-10-14 13:38:55,126 | ERROR | ntDispatcherImpl | NeutronL3Adapter                 | 392 - org.opendaylight.ovsdb.openstack.net-virt - 1.2.1.SNAPSHOT | ProgramStaticArp failed for mac:FA:16:3E:E0:A8:B5 addr:fd14:5ac7:ba3::1 dpid:209308480409166 segOrOfPort:1083 action:ADD status:Not Implemented: Not Implemented (0)
    > 2015-10-14 13:38:55,126 | ERROR | ntDispatcherImpl | EventDispatcher                  | 392 - org.opendaylight.ovsdb.openstack.net-virt - 1.2.1.SNAPSHOT | Exception in dispatching event NorthboundEvent [handler=NEUTRON_PORT, action=ADD, port=NeutronPort [portUUID=4b19acf4-d644-4fe7-8643-852c25cbf604, networkUUID=821f7a2b-b991-48b0-a39c-b0ef264bd321, name=, adminStateUp=true, status=ACTIVE, macAddress=FA:16:3E:E0:A8:B5, fixedIPs=[Neutron_IPs{ipAddress='fd14:5ac7:ba3::1', subnetUUID='54a7f233-1fdb-4d40-bd44-275f180e9a64'}], deviceID=738d6a7c-43bd-469d-bfed-6bcc6ffe5dca, deviceOwner=network:router_interface, tenantID=dc27e3a1cff64a1cb85c7f24899c3eee, securityGroups=[], bindinghostID=, bindingvnicType=normal, bindingvnicType=normal], subnet=null, router=null, routerInterface=null, floatingIP=null, network=null, loadBalancer=null, loadBalancerPool=null, loadBalancerPoolMember=null]
    > java.lang.IllegalArgumentException: Supplied value "fd14:5ac7:ba3::/64" does not match required pattern "^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])/(([0-9])|([1-2][0-9])|(3[0-2]))$"
    >         at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)[64:com.google.guava:18.0.0]
    >         at org.opendaylight.yang.gen.v1.urn.ietf.params.xml.ns.yang.ietf.inet.types.rev100924.Ipv4Prefix.<init>(Ipv4Prefix.java:49)[216:org.opendaylight.mdsal.model.ietf-inet-types:2010.9.24.8-SNAPSHOT]
    >         at org.opendaylight.ovsdb.openstack.netvirt.providers.openflow13.services.OutboundNatService.programIpRewriteExclusion(OutboundNatService.java:167)[393:org.opendaylight.ovsdb.openstack.net-virt-providers:1.2.1.SNAPSHOT]
    >         at org.opendaylight.ovsdb.openstack.netvirt.impl.NeutronL3Adapter.programIpRewriteExclusionStage2(NeutronL3Adapter.java:1143)[392:org.opendaylight.ovsdb.openstack.net-virt:1.2.1.SNAPSHOT]
    >         at org.opendaylight.ovsdb.openstack.netvirt.impl.NeutronL3Adapter.programIpRewriteExclusionStage1(NeutronL3Adapter.java:1128)[392:org.opendaylight.ovsdb.openstack.net-virt:1.2.1.SNAPSHOT]
    >         at org.opendaylight.ovsdb.openstack.netvirt.impl.NeutronL3Adapter.programFlowsForNeutronRouterInterface(NeutronL3Adapter.java:807)[392:org.opendaylight.ovsdb.openstack.net-virt:1.2.1.SNAPSHOT]
    >         at org.opendaylight.ovsdb.openstack.netvirt.impl.NeutronL3Adapter.handleNeutronRouterInterfaceEvent(NeutronL3Adapter.java:298)[392:org.opendaylight.ovsdb.openstack.net-virt:1.2.1.SNAPSHOT]
    >         at org.opendaylight.ovsdb.openstack.netvirt.impl.NeutronL3Adapter.handleNeutronPortEvent(NeutronL3Adapter.java:245)[392:org.opendaylight.ovsdb.openstack.net-virt:1.2.1.SNAPSHOT]
    >         at org.opendaylight.ovsdb.openstack.netvirt.PortHandler.doNeutronPortCreated(PortHandler.java:66)[392:org.opendaylight.ovsdb.openstack.net-virt:1.2.1.SNAPSHOT]
    >         at org.opendaylight.ovsdb.openstack.netvirt.PortHandler.processEvent(PortHandler.java:161)[392:org.opendaylight.ovsdb.openstack.net-virt:1.2.1.SNAPSHOT]
    >         at org.opendaylight.ovsdb.openstack.netvirt.impl.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:95)[392:org.opendaylight.ovsdb.openstack.net-virt:1.2.1.SNAPSHOT]
    >         at org.opendaylight.ovsdb.openstack.netvirt.impl.EventDispatcherImpl.access$200(EventDispatcherImpl.java:28)[392:org.opendaylight.ovsdb.openstack.net-virt:1.2.1.SNAPSHOT]
    >         at org.opendaylight.ovsdb.openstack.netvirt.impl.EventDispatcherImpl$1.run(EventDispatcherImpl.java:57)[392:org.opendaylight.ovsdb.openstack.net-virt:1.2.1.SNAPSHOT]
    >         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_60]
    >         at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_60]
    >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_60]
    >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_60]
    >         at java.lang.Thread.run(Thread.java:745)[:1.8.0_60]

    Change-Id: I1559667adde1c14b5627df3b7212e404998ce897
    Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>

commit 241ccfe97218b053f1ae09a1d7568df551b85551
Author: Maxime Millette-Coulombe <mmcoulombe@inocybe.com>
Date:   Wed Jul 22 11:53:30 2015 -0400

    First pass for ovsdb-ui

    Revamp of the work already done. Adding a draft of a
    logical topology viewer. The old code is still in this
    commit because the works done before will be reuse.

    Change-Id: Ia3a86cb0370cfad2ef3c2a156b412b9e029c3bf9
    Signed-off-by: Maxime Millette-Coulombe <mmcoulombe@inocybe.com>

commit 26ed35648c8fcea96674a1f6e310f9d7930c09c8
Author: Rashmi Pujar <rpujar@inocybe.com>
Date:   Wed Oct 14 15:03:17 2015 -0400

    UT for southbound/transactions/md - set 5

    11. OvsdbPortRemoveCommand.java
    12. TransactionInvokerImpl.java
    13. OvsdbPortUpdateCommand.java

    Change-Id: Icd9ad76e482de5408650916f6bbf5bc73dc297c8
    Signed-off-by: Rashmi Pujar <rpujar@inocybe.com>

commit 5c63f9ab23bd98686a93e7f745689cf95b152a0c
Author: Sam Hague <shague@redhat.com>
Date:   Wed Oct 14 13:29:47 2015 -0400

    neuter NetvirtSfcIT

    Change-Id: Iaca49229b1c594a9e2b5659048319880643887ec
    Signed-off-by: Sam Hague <shague@redhat.com>

commit 1b7724f1fe1bae26cc0ffe8f86f83f3ea10fd626
Merge: 29eeb86 09a89ea
Author: Sam Hague <shague@redhat.com>
Date:   Wed Oct 14 15:32:29 2015 +0000

    Merge "add ovsdb-sfc feature to test feature"

commit 09a89eaa4496580769faf0564a0b174040682c5d
Author: Sam Hague <shague@redhat.com>
Date:   Wed Oct 14 10:49:05 2015 -0400

    add ovsdb-sfc feature to test feature

    Change-Id: I55c2df5791983998f696054b7728b7d1be696e33
    Signed-off-by: Sam Hague <shague@redhat.com>

commit 29eeb865eab297a9d9642d8816dc6ffdbcd42f1f
Merge: 378e785 864ac9f
Author: Sam Hague <shague@redhat.com>
Date:   Wed Oct 14 13:19:56 2015 +0000

    Merge "Add capability on southbound to NetvirtSfc"

commit 864ac9f57ab4f369e8237d1e55c3121784e86915
Author: Sam Hague <shague@redhat.com>
Date:   Wed Oct 14 09:02:51 2015 -0400

    Add capability on southbound to NetvirtSfc

    Change-Id: Iffd6b7b27e701fdfa3bf663421ba72945562d0f1
    Signed-off-by: Sam Hague <shague@redhat.com>

commit 378e78556b82bc756069145194c3cf606aa4aba0
Merge: a8c8f4a ff01d7b
Author: Sam Hague <shague@redhat.com>
Date:   Wed Oct 14 04:55:31 2015 +0000

    Merge "Workaround to fix net-virt-it"

commit ff01d7b11f98e0d5cabd5bd77a8f0dfcfe12675a
Author: Sam Hague <shague@redhat.com>
Date:   Wed Oct 14 00:23:59 2015 -0400

    Workaround to fix net-virt-it

    Change-Id: I10838b993f60b5e3859780d7d9f7b4c3630e312a
    Signed-off-by: Sam Hague <shague@redhat.com>

commit a8c8f4a5010d6a2b565ca411c3541f9698f3ad49
Merge: cfb6abf ffa3c96
Author: Sam Hague <shague@redhat.com>
Date:   Tue Oct 13 13:10:11 2015 +0000

    Merge "UT for southbound/transactions/md - set 4"

commit cfb6abf8d000ebca1f7585e1cda58cd82e21f329
Author: Anil Vishnoi <vishnoianil@gmail.com>
Date:   Tue Oct 13 13:34:24 2015 +0530

    Fix issue that was causing integration test failure.

    In case of controller initiated connection, iid stamping
    was not happening. Before clustering code merge, iid stamping
    was done in updateData(), but after clustering code merge,
    it does not allow to make any changes to the device till
    owner of the device is selected by EntityOnwershipService,
    so updateData() was not stamping the iid to swtich. With this
    fix, once owner of the device is selected, it explictly stamp
    iid to the switch.

    NOTE: we should revert following patch before merging this patch
    https://git.opendaylight.org/gerrit/#/c/28309/1

    I ran the integration suit locally and it passes all the tests

    [main] INFO org.ops4j.pax.exam.spi.reactors.ReactorManager - suite finished
    Tests run: 22, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 288.094 sec - in org.opendaylight.ovsdb.southbound.it.SouthboundIT

    Results :

    Tests run: 22, Failures: 0, Errors: 0, Skipped: 0

    Change-Id: I35d6e0a4fa94eef019420e9b9603873d5088a934
    Signed-off-by: Anil Vishnoi <vishnoianil@gmail.com>

commit 91c15602a6323fb4dec0dc2605c853689844aec6
Author: Flavio Fernandes <ffernand@redhat.com>
Date:   Tue Oct 13 11:04:46 2015 +0000

    Revert "Temp workaround to debug southbound IT"

    This reverts commit 149c5bfb602e91f07c2b98f9509d317be8fcaa3c.

    Change-Id: I78aa7b506f32e37b65cae1bfb24bbb360c5359ad
    Signed-off-by: Sam Hague <shague@redhat.com>
    Signed-off-by: Anil Vishnoi <vishnoianil@gmail.com>
    Signed-off-by: Flavio Fernandes <ffernand@redhat.com>

commit 149c5bfb602e91f07c2b98f9509d317be8fcaa3c
Author: Sam Hague <shague@redhat.com>
Date:   Mon Oct 12 20:50:25 2015 -0400

    Temp workaround to debug southbound IT

    It is a timing change from the clustering code not taking into account some crazy existing code.

    This patch has a workaround that works in my local tests. I will merge it temporarily to see if the jenkins builds are good.

    Will work with Anil and Flavio on a long term solution.

    Old code:

    write ovsdb node to config ->
    -> dcl ->
    -> connect -> connect -> connectedButCallbacksNotRegistered -> putConnectionInstance
    -> updateData -> OvsdbNodeUpdateCommand - > ovsdb node - set Open_vSwitch external_ids
    *** key here is that the putConnectionInstance happened earlier in connect so now the OvsdbNodeUpdateCommand gets a chance to run and write the externalIds to the Open_vSwitch table
    ...
    OvsdbMonitorCallback -> OpenVSwitchUpdateCommand - > writes node to operational
    *** key here is that the iid (nodePath) is found by looking for the externalIds. If found, since it was written earlier, then it is used, if not the backup of using the uuid of the node is used. The IT expects the externalIds value to be there and that is the one with the form ip:port.

    In the new code:
    - putConnectionInstance() does not happen until the handleOwnership completes - too late since the updateData is processed before that
    - updateData doesn't do anything, complains about not finding client since the connectionInstance was not written earlier, therefore the externalIds are not written
    - OpenVSwitchUpdateCommand ends up using the wrong iid of the form using the uuid since the externalIds were not written.

    Change-Id: Iafbb8c4fa3dd5708f4c4bd3242e27ec72a4b4c6e
    Signed-off-by: Sam Hague <shague@redhat.com>

commit a536890a609e1b28cce86a616c11447b839c1348
Author: Andre Fredette <afredette@redhat.com>
Date:   Tue Oct 6 17:33:15 2015 -0400

    Bug 4144 - Periodic ARP resolver should use unicast MAC destination
    address whenever possible; instead of broadcast

    Modified ArpResolver and GatewayMacResolverService to use the unicast DA
    when known.  The code treats the DA as known for a new ARP request if
    one of the last N=2 ARP request was answered.

    Change-Id: I2bd7791b74d41e2838edf59d6edc510b63f3c40b
    Signed-off-by: Andre Fredette <afredette@redhat.com>

commit 1c4bfda9a0f94a2a97c58a918f945f4e1e3d4688
Author: Vishal Thapar <vishal.thapar@ericsson.com>
Date:   Mon Oct 12 14:22:57 2015 +0530

    hwvtep: version bump to 1.2.1

    Update hwvtep poms as per this:
    https://git.opendaylight.org/gerrit/#/c/25574/

    Change-Id: I651a4e475e9bf243497ce07386e7418141f2fc3c
    Signed-off-by: Vishal Thapar <vishal.thapar@ericsson.com>

commit 685f586c67dc369259fc53a001f3d8297c6d8351
Author: Sam Hague <shague@redhat.com>
Date:   Fri Oct 9 16:22:56 2015 -0400

    Add setting controller for sfc it

    This patch adds setting the controller so that flows can be pushed to the switches.

    Use the following to initate the tests:

    start an ovsdb node and set it to be in passive mode: sudo ovs-vsctl set-manager ptcp:6640
    cd .../net-virt-sfc/it
    mvn -Dit.test=NetvirtSfcIT#testDoIt verify -Pintegrationtest -Dovsdbserver.ipaddress=192.168.120.31

    The above will connect to the node and set's it controller to ODL.

    Change-Id: Ibf307b668535e47fe80ba0a8b7403e53d7a40ccb
    Signed-off-by: Sam Hague <shague@redhat.com>

commit ffa3c96aab514cfaba4e0eb543fe6956d3dfdb13
Author: Rashmi Pujar <rpujar@inocybe.com>
Date:   Fri Oct 9 12:37:06 2015 -0400

    UT for southbound/transactions/md - set 4

    8. OvsdbManagersUpdateCommand.java
    9. OvsdbNodeRemoveCommand.java
    10. OvsdbOperationalCommandAggregator.java

    Change-Id: I4597340cb871fb6b8558f2632ad71423a3cb8176
    Signed-off-by: Rashmi Pujar <rpujar@inocybe.com>

commit f7f42fbacd178a843009a07bb21816afa83707b3
Author: sangeeta.maurya <sangeeta.maurya@hp.com>
Date:   Fri Oct 9 04:58:00 2015 +0545

    All TCP & UDP SG Rules : Implementation and Unit tests added.

    Change-Id: I4a00740fed78ab416fe22214fa7542ae7036f6fc
    Signed-off-by: sangeeta.maurya <sangeeta.maurya@hp.com>

Change-Id: I95183dca8f6a8f628c5937e94ae7a098c536d14f
Signed-off-by: Anil Vishnoi <vishnoianil@gmail.com>